# python v3.12
python_version: py311

# model
model_name: OmniParser
description: Parse user interface screenshots into structured elements.
model_class_name: Model
model_module_dir: model
model_metadata: {}

# pip requirements
requirements:
  - pillow==11.1.0
  - torch==2.6.0
  - torchvision==0.21.0
  - numpy==1.26.4
  - matplotlib==3.10.0
  - easyocr==1.7.2
  - supervision==0.18.0
  - ultralytics==8.3.70
  - transformers==4.49.0
  - timm==1.0.14
  - einops==0.8.0

# debian packages
system_packages:
  - libgl1-mesa-dev

# download weights from S3
external_data:
  - url: https://computerlm-public.s3.us-east-1.amazonaws.com/omniparser.tar.gz
    local_data_path: omniparser.tar.gz
  - url: https://computerlm-public.s3.us-east-1.amazonaws.com/easyocr.tar.gz
    local_data_path: easyocr.tar.gz

# unzip weights
build_commands:
  - mkdir -p data/omniparser data/easyocr
  - tar -xzvf data/omniparser.tar.gz -C data/omniparser/
  - tar -xzvf data/easyocr.tar.gz -C data/easyocr/

# inference resources
resources:
  cpu: "4"
  memory: 16Gi
  use_gpu: true
  accelerator: A100

runtime:
  predict_concurrency: 5
  enable_debug_logs: true

# additional config
external_package_dirs: []
secrets: {}
